{
	"success": true,
		"code": "OK",
			"msg": "Operation succeeded.",
				"timestamp": 1529583587121,
					"data": [
						{
							"withdrawMinFee": 0.5,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Kucoin Shares",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "KCS"
						},
						{
							"withdrawMinFee": 0.001,
							"coinType": null,
							"withdrawMinAmount": 0.002,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://blockchain.info/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 3,
							"infoUrl": null,
							"enable": true,
							"name": "Bitcoin",
							"tradePrecision": 8,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "BTC"
						},
						{
							"withdrawMinFee": 0.01,
							"coinType": "ETH",
							"withdrawMinAmount": 0.1,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Ethereum",
							"tradePrecision": 7,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "ETH"
						},
						{
							"withdrawMinFee": 0.0,
							"coinType": "NEO",
							"withdrawMinAmount": 1.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://neoscan.io/transaction/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 6,
							"infoUrl": null,
							"enable": true,
							"name": "NEO",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "NEO"
						},
						{
							"withdrawMinFee": 20.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "I-House Token",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "IHT"
						},
						{
							"withdrawMinFee": 50.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 400.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "TRAXIA",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "TMT"
						},
						{
							"withdrawMinFee": 0.05,
							"coinType": null,
							"withdrawMinAmount": 5.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://raiblocks.net/block/index.php?h={txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Nano",
							"tradePrecision": 6,
							"depositRemark": "",
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "XRB"
						},
						{
							"withdrawMinFee": 1.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Fortuna",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "FOTA"
						},
						{
							"withdrawMinFee": 2.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 15.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Arcblock",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "ABT"
						},
						{
							"withdrawMinFee": 2.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 5.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "SingularityNET",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "AGI"
						},
						{
							"withdrawMinFee": 2.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Aigang",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "AIX"
						},
						{
							"withdrawMinFee": 10.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Enjin Coin",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "ENJ"
						},
						{
							"withdrawMinFee": 3.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 20.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Experty",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "EXY"
						},
						{
							"withdrawMinFee": 5.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 30.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Havven",
							"tradePrecision": 8,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "HAV"
						},
						{
							"withdrawMinFee": 0.5,
							"coinType": "ERC20",
							"withdrawMinAmount": 5.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "High Performance Blockch",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "HPB"
						},
						{
							"withdrawMinFee": 30.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 200.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "JET8",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "J8T"
						},
						{
							"withdrawMinFee": 1.0,
							"coinType": "NEP",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://neotracker.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Red Pulse",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "RPX"
						},
						{
							"withdrawMinFee": 10.0,
							"coinType": "NEP",
							"withdrawMinAmount": 50.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://neotracker.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "THEKEY",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "TKY"
						},
						{
							"withdrawMinFee": 1.0,
							"coinType": "NEP",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://neotracker.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Trinity",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "TNC"
						},
						{
							"withdrawMinFee": 0.7,
							"coinType": null,
							"withdrawMinAmount": 4.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://explorer.wanchain.org/block/trans/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Wanchain",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "WAN"
						},
						{
							"withdrawMinFee": 1.0,
							"coinType": "NEP",
							"withdrawMinAmount": 20.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://neotracker.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Zeepin",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "ZPT"
						},
						{
							"withdrawMinFee": 10.0,
							"coinType": "NEP",
							"withdrawMinAmount": 300.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://neotracker.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Alphacat",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "ACAT"
						},
						{
							"withdrawMinFee": 20.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "DOCK",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "DOCK"
						},
						{
							"withdrawMinFee": 20.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 50.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "EthLend",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "LEND"
						},
						{
							"withdrawMinFee": 0.1,
							"coinType": "ERC20",
							"withdrawMinAmount": 1.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Chronobank",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "TIME"
						},
						{
							"withdrawMinFee": 3.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 20.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Credits",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "CS"
						},
						{
							"withdrawMinFee": 50.0,
							"coinType": "gochain",
							"withdrawMinAmount": 350.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://explorer.gochain.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "GoChain",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "GO"
						},
						{
							"withdrawMinFee": 1.0,
							"coinType": null,
							"withdrawMinAmount": 100.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://browser.achain.com/#/tradeInfo/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "AChain",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "ACT"
						},
						{
							"withdrawMinFee": 3.0,
							"coinType": "NEP",
							"withdrawMinAmount": 25.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://neotracker.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Aphelion",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "APH"
						},
						{
							"withdrawMinFee": 1.8,
							"coinType": "ERC20",
							"withdrawMinAmount": 12.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Aeron",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "ARN"
						},
						{
							"withdrawMinFee": 25.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "aXpire",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "AXP"
						},
						{
							"withdrawMinFee": 3.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 20.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Bread",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "BRD"
						},
						{
							"withdrawMinFee": 1.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "CanYa",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "CAN"
						},
						{
							"withdrawMinFee": 20.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "BitClave",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "CAT"
						},
						{
							"withdrawMinFee": 5.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 50.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "CashBet Coin",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "CBC"
						},
						{
							"withdrawMinFee": 25.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 170.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "CoinPoker",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "CHP"
						},
						{
							"withdrawMinFee": 30.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "CargoX",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "CXO"
						},
						{
							"withdrawMinFee": 20.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Datum",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "DAT"
						},
						{
							"withdrawMinFee": 1.0,
							"coinType": "NEP",
							"withdrawMinAmount": 5.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://neotracker.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "DeepBrain Chain",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "DBC"
						},
						{
							"withdrawMinFee": 3.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 20.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "EncrypGen",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "DNA"
						},
						{
							"withdrawMinFee": 100.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 2000.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "DATA",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "DTA"
						},
						{
							"withdrawMinFee": 50.0,
							"coinType": null,
							"withdrawMinAmount": 350.0,
							"withdrawRemark": "If you need payment_id in transfer, please place payment_id behind your receiving address and separate with @, eg. Address@payment_id | 提现如需payment_id，可以将payment_id放在收款地址后面，并用@符号隔开。举例: Address@payment_id\r\n",
							"orgAddress": "etnjvMPvGM68TZp59KDfWvQoNS7NFaEc9296CK4pSrfA4j5KgTguz5sZNEwC2KMW6iEn8gML7vASrT3gLxD3n9zs3M2PxMYVyH",
							"txUrl": "https://blockexplorer.electroneum.com/tx/{txId}",
							"userAddressName": "Payment ID",
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Electroneum",
							"tradePrecision": 2,
							"depositRemark": "Please send ETN to this address: etnjvMPvGM68TZp59KDfWvQoNS7NFaEc9296CK4pSrfA4j5KgTguz5sZNEwC2KMW6iEn8gML7vASrT3gLxD3n9zs3M2PxMYVyH Note: The practical deposit wallet address below is payment_id. Please specify payment_id for deposit, or the deposit will fail to be credited.\r\n",
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "ETN"
						},
						{
							"withdrawMinFee": 0.5,
							"coinType": "ERC20",
							"withdrawMinAmount": 1.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "INS Ecosystem",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "INS"
						},
						{
							"withdrawMinFee": 5.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Jibrel Network",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "JNT"
						},
						{
							"withdrawMinFee": 20.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 700.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Lympo",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "LYM"
						},
						{
							"withdrawMinFee": 50.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 300.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Shivom",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "OMX"
						},
						{
							"withdrawMinFee": 0.1,
							"coinType": "NEP",
							"withdrawMinAmount": 0.2,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://neotracker.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Ontology",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "ONT"
						},
						{
							"withdrawMinFee": 10.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 90.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "QuarkChain",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "QKC"
						},
						{
							"withdrawMinFee": 1.0,
							"coinType": "NEP",
							"withdrawMinAmount": 5.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://neotracker.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Qlink",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "QLC"
						},
						{
							"withdrawMinFee": 5.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 40.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "SIRIN LABS Token",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "SRN"
						},
						{
							"withdrawMinFee": 500.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 5000.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Telcoin",
							"tradePrecision": 2,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "TEL"
						},
						{
							"withdrawMinFee": 100.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 900.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "TE-FOOD",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "TFD"
						},
						{
							"withdrawMinFee": 17.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 110.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "WePower",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "WPR"
						},
						{
							"withdrawMinFee": 70.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 500.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "DATx",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "DATX"
						},
						{
							"withdrawMinFee": 50.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Dent",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "DENT"
						},
						{
							"withdrawMinFee": 32.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 210.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Electrify.Asia",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "ELEC"
						},
						{
							"withdrawMinFee": 5.0,
							"coinType": null,
							"withdrawMinAmount": 10.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": null,
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "GALA",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": false,
							"coin": "GALA"
						},
						{
							"withdrawMinFee": 50.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 1000.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "IOStoken",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "IOST"
						},
						{
							"withdrawMinFee": 30.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 200.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "IoTeX",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "IOTX"
						},
						{
							"withdrawMinFee": 50.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 300.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "LALA World",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "LALA"
						},
						{
							"withdrawMinFee": 10.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Loom Network",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "LOOM"
						},
						{
							"withdrawMinFee": 15.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Decentraland",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "MANA"
						},
						{
							"withdrawMinFee": 15.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 500.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "OPEN Platform",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "OPEN"
						},
						{
							"withdrawMinFee": 0.5,
							"coinType": null,
							"withdrawMinAmount": 1.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://chainz.cryptoid.info/pura/tx.dws?{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Pura",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "PURA"
						},
						{
							"withdrawMinFee": 4.0,
							"coinType": "NEP",
							"withdrawMinAmount": 25.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://neoscan.io/transaction/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Phantasma",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "SOUL"
						},
						{
							"withdrawMinFee": 1.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "TomoChain",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "TOMO"
						},
						{
							"withdrawMinFee": 14.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 90.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "OriginTrail",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "TRAC"
						},
						{
							"withdrawMinFee": 8.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 55.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "SophiaTX",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "SPHTX"
						},
						{
							"withdrawMinFee": 30.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "carVertical",
							"tradePrecision": 2,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "CV"
						},
						{
							"withdrawMinFee": 10.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 20.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Adbank",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "ADB"
						},
						{
							"withdrawMinFee": 10.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 200.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Block Array",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "ARY"
						},
						{
							"withdrawMinFee": 1000.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 8000.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "BABB",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "BAX"
						},
						{
							"withdrawMinFee": 1.0,
							"coinType": null,
							"withdrawMinAmount": 5.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://bosradar.com/transaction/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "BOScoin",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "BOS"
						},
						{
							"withdrawMinFee": 2.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Centra",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": false,
							"coin": "CTR"
						},
						{
							"withdrawMinFee": 12.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 80.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Debitum Network",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "DEB"
						},
						{
							"withdrawMinFee": 2.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 20.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "aelf",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "ELF"
						},
						{
							"withdrawMinFee": 4.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 50.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Gladius Token",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "GLA"
						},
						{
							"withdrawMinFee": 0.5,
							"coinType": "ERC20",
							"withdrawMinAmount": 50.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Hawala.Today",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "HAT"
						},
						{
							"withdrawMinFee": 3.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "IUNGO",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "ING"
						},
						{
							"withdrawMinFee": 1.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 50.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "IoT Chain",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "ITC"
						},
						{
							"withdrawMinFee": 50.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 1000.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "SelfKey",
							"tradePrecision": 4,
							"depositRemark": "Please be aware that this address is only for depositing SelfKey (KEY), depositing other assets into this address will cause fund loss and it's not revertible.",
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "KEY"
						},
						{
							"withdrawMinFee": 2.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Matrix AI Network",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "MAN"
						},
						{
							"withdrawMinFee": 10.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 20.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Medicalchain",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "MTN"
						},
						{
							"withdrawMinFee": 100.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 500.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Odyssey",
							"tradePrecision": 2,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "OCN"
						},
						{
							"withdrawMinFee": 10.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 1.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Po.et",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": false,
							"coin": "POE"
						},
						{
							"withdrawMinFee": 10.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "SunContract",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "SNC"
						},
						{
							"withdrawMinFee": 5.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Trade Token",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "TIO"
						},
						{
							"withdrawMinFee": 10.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "UTRUST",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "UTK"
						},
						{
							"withdrawMinFee": 0.1,
							"coinType": null,
							"withdrawMinAmount": 1.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://solaris.blockexplorer.pro/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Solaris",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "XLR"
						},
						{
							"withdrawMinFee": 50.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 300.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Zilliqa",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "ZIL"
						},
						{
							"withdrawMinFee": 20.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 200.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Cappasity",
							"tradePrecision": 2,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "CAPP"
						},
						{
							"withdrawMinFee": 70.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 500.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "SwissBorg",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "CHSB"
						},
						{
							"withdrawMinFee": 5.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "CoinFi",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "COFI"
						},
						{
							"withdrawMinFee": 6.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 50.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "DADI",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "DADI"
						},
						{
							"withdrawMinFee": 0.002,
							"coinType": null,
							"withdrawMinAmount": 0.05,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://chainz.cryptoid.info/dash/tx.dws?{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Dash",
							"tradePrecision": 8,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "DASH"
						},
						{
							"withdrawMinFee": 3.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "eBitcoin",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "EBTC"
						},
						{
							"withdrawMinFee": 4.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "LOCIcoin",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "LOCI"
						},
						{
							"withdrawMinFee": 30.0,
							"coinType": "MOBI",
							"withdrawMinAmount": 200.0,
							"withdrawRemark": "If you need Memo in transfer, please place Memo behind your receiving address and separate with @. For example: Address@memo | 如果需要转账memo等备注信息，可以放在收款地址后面，并使用@符号隔开。举例：Address@memo",
							"orgAddress": "GBJNV2MQA7M5GNBRDFW46JLXIN7ZLYVVM4UW4CWDZO4KZKXIXCRYHMH2",
							"txUrl": "https://stellar.expert/explorer/public/tx/{txid}",
							"userAddressName": "MEMO",
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Mobius",
							"tradePrecision": 4,
							"depositRemark": "Please send MOBI to this address: \r\nGBJNV2MQA7M5GNBRDFW46JLXIN7ZLYVVM4UW4CWDZO4KZKXIXCRYHMH2\r\nNote: The practical deposit wallet address below is Memo. Please specify Memo for deposit, or the transfer may fail to be credited.",
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "MOBI"
						},
						{
							"withdrawMinFee": 5.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Blockport",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "BPT"
						},
						{
							"withdrawMinFee": 3.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Covesting",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "COV"
						},
						{
							"withdrawMinFee": 140.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 1000.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Gatcoin",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "GAT"
						},
						{
							"withdrawMinFee": 0.5,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Hacken",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "HKN"
						},
						{
							"withdrawMinFee": 1.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Oyster Pearl",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "PRL"
						},
						{
							"withdrawMinFee": 300.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 2000.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "SpherePay",
							"tradePrecision": 2,
							"depositRemark": null,
							"enableWithdraw": false,
							"enableDeposit": false,
							"coin": "SAY"
						},
						{
							"withdrawMinFee": 1.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "TrueFlip",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "TFL"
						},
						{
							"withdrawMinFee": 8.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "WAX",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "WAX"
						},
						{
							"withdrawMinFee": 0.5,
							"coinType": "ERC20",
							"withdrawMinAmount": 5.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Aion",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "AION"
						},
						{
							"withdrawMinFee": 35.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 150.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "KickCoin",
							"tradePrecision": 4,
							"depositRemark": "Please be aware that this wallet address does not support to receive KICK bonus.",
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "KICK"
						},
						{
							"withdrawMinFee": 20.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Restart Energy",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "MWAT"
						},
						{
							"withdrawMinFee": 40.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 300.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "HEROcoin",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "PLAY"
						},
						{
							"withdrawMinFee": 40.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Pareto Network",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "PARETO"
						},
						{
							"withdrawMinFee": 2.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Revain",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "R"
						},
						{
							"withdrawMinFee": 5.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "LAToken",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "LA"
						},
						{
							"withdrawMinFee": 20.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 150.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}\r\n",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "AURORA",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "AOA"
						},
						{
							"withdrawMinFee": 5.0E-4,
							"coinType": null,
							"withdrawMinAmount": 0.01,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "http://blockdozer.com/insight/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 6,
							"infoUrl": null,
							"enable": true,
							"name": "Bitcoin Cash",
							"tradePrecision": 8,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "BCH"
						},
						{
							"withdrawMinFee": 2.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 5.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Change",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "CAG"
						},
						{
							"withdrawMinFee": 0.005,
							"coinType": null,
							"withdrawMinAmount": 0.01,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": null,
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Bitcoin God",
							"tradePrecision": 8,
							"depositRemark": null,
							"enableWithdraw": false,
							"enableDeposit": false,
							"coin": "GOD"
						},
						{
							"withdrawMinFee": 30.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "CoinMeet",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": false,
							"coin": "MEE"
						},
						{
							"withdrawMinFee": 0.5,
							"coinType": "ERC20",
							"withdrawMinAmount": 5.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Modum",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "MOD"
						},
						{
							"withdrawMinFee": 5.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Publica",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "PBL"
						},
						{
							"withdrawMinFee": 0.1,
							"coinType": "ERC20",
							"withdrawMinAmount": 0.5,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Populous",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "PPT"
						},
						{
							"withdrawMinFee": 5.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Quantstamp",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "QSP"
						},
						{
							"withdrawMinFee": 5.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "SONM",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "SNM"
						},
						{
							"withdrawMinFee": 10.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "SportyCo",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "SPF"
						},
						{
							"withdrawMinFee": 0.5,
							"coinType": null,
							"withdrawMinAmount": 10.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "http://aschd.org/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Asch",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "XAS"
						},
						{
							"withdrawMinFee": 50.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Bounty0x",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "BNTY"
						},
						{
							"withdrawMinFee": 0.01,
							"coinType": null,
							"withdrawMinAmount": 1.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://explorer.btcprivate.org/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Bitcoin Private",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": false,
							"enableDeposit": false,
							"coin": "BTCP"
						},
						{
							"withdrawMinFee": 1.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Dragonchain",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "DRGN"
						},
						{
							"withdrawMinFee": 10.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 20.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "CoinMeet",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": false,
							"coin": "MEET"
						},
						{
							"withdrawMinFee": 1.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 1.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Nuls",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "NULS"
						},
						{
							"withdrawMinFee": 0.5,
							"coinType": "ERC20",
							"withdrawMinAmount": 5.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "ClearPoll",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "POLL"
						},
						{
							"withdrawMinFee": 1.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 2.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Power Ledger",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "POWR"
						},
						{
							"withdrawMinFee": 20.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Snovio",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "SNOV"
						},
						{
							"withdrawMinFee": 0.1,
							"coinType": null,
							"withdrawMinAmount": 1.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "http://onionexplorer.youngwebsolutions.com:3001/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "DeepOnion",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "ONION"
						},
						{
							"withdrawMinFee": 0.01,
							"coinType": null,
							"withdrawMinAmount": 0.1,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "http://gastracker.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Ethereum Classic",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "ETC"
						},
						{
							"withdrawMinFee": 3.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 5.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Ambrosus",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "AMB"
						},
						{
							"withdrawMinFee": 5.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 1.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Stox",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": false,
							"coin": "STX"
						},
						{
							"withdrawMinFee": 3.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 5.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Elixir",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "ELIX"
						},
						{
							"withdrawMinFee": 20.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "STK",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "STK"
						},
						{
							"withdrawMinFee": 10.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 20.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Flixxo",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "FLIXX"
						},
						{
							"withdrawMinFee": 0.1,
							"coinType": "ERC20",
							"withdrawMinAmount": 1.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Genesis Vision",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "GVT"
						},
						{
							"withdrawMinFee": 0.005,
							"coinType": null,
							"withdrawMinAmount": 0.01,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "http://explorer.btcd.io/#/TX?TX={txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 6,
							"infoUrl": null,
							"enable": true,
							"name": "Bitcoin Diamond",
							"tradePrecision": 8,
							"depositRemark": null,
							"enableWithdraw": false,
							"enableDeposit": false,
							"coin": "BCD"
						},
						{
							"withdrawMinFee": 0.5,
							"coinType": "ERC20",
							"withdrawMinAmount": 1.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Confido",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": false,
							"enableDeposit": false,
							"coin": "CFD"
						},
						{
							"withdrawMinFee": 0.0,
							"coinType": "GAS",
							"withdrawMinAmount": 0.2,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://neoscan.io/transaction/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 6,
							"infoUrl": null,
							"enable": true,
							"name": "NeoGas",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "GAS"
						},
						{
							"withdrawMinFee": 2.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Horizon State",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "HST"
						},
						{
							"withdrawMinFee": 0.5,
							"coinType": "ERC20",
							"withdrawMinAmount": 1.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Raiden Network",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "RDN"
						},
						{
							"withdrawMinFee": 4.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 25.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "SHL",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "SHL"
						},
						{
							"withdrawMinFee": 2.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Substratum",
							"tradePrecision": 2,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "SUB"
						},
						{
							"withdrawMinFee": 5.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Unikoin Gold",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "UKG"
						},
						{
							"withdrawMinFee": 0.1,
							"coinType": "ERC20",
							"withdrawMinAmount": 0.2,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Walton",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "WTC"
						},
						{
							"withdrawMinFee": 0.1,
							"coinType": null,
							"withdrawMinAmount": 5.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "http://explorer.nebl.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Neblio",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "NEBL"
						},
						{
							"withdrawMinFee": 3.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Polymath",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "POLY"
						},
						{
							"withdrawMinFee": 2.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 5.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "RChain",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "RHOC"
						},
						{
							"withdrawMinFee": 2.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "VeChain",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "VEN"
						},
						{
							"withdrawMinFee": 10.0,
							"coinType": null,
							"withdrawMinAmount": 50.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "http://omniexplorer.info/lookuptx.aspx?txid={txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 3,
							"infoUrl": null,
							"enable": true,
							"name": "USDT",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "USDT"
						},
						{
							"withdrawMinFee": 0.005,
							"coinType": null,
							"withdrawMinAmount": 0.01,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://btgexp.com/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Bitcoin Gold",
							"tradePrecision": 8,
							"depositRemark": null,
							"enableWithdraw": false,
							"enableDeposit": false,
							"coin": "BTG"
						},
						{
							"withdrawMinFee": 0.5,
							"coinType": null,
							"withdrawMinAmount": 1.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://digiexplorer.info/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Digibyte",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "DGB"
						},
						{
							"withdrawMinFee": 0.5,
							"coinType": "ERC20",
							"withdrawMinAmount": 1.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Everex",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": false,
							"coin": "EVX"
						},
						{
							"withdrawMinFee": 0.01,
							"coinType": null,
							"withdrawMinAmount": 0.1,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "http://hshare-explorer.h.cash/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 6,
							"infoUrl": null,
							"enable": true,
							"name": "Hshare",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "HSR"
						},
						{
							"withdrawMinFee": 0.5,
							"coinType": "ERC20",
							"withdrawMinAmount": 0.5,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Kyber Network",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "KNC"
						},
						{
							"withdrawMinFee": 0.001,
							"coinType": null,
							"withdrawMinAmount": 0.1,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://live.blockcypher.com/ltc/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 6,
							"infoUrl": null,
							"enable": true,
							"name": "Litecoin",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "LTC"
						},
						{
							"withdrawMinFee": 10.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 20.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Monetha",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "MTH"
						},
						{
							"withdrawMinFee": 0.1,
							"coinType": "ERC20",
							"withdrawMinAmount": 0.2,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "OmiseGO",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "OMG"
						},
						{
							"withdrawMinFee": 10.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 20.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Request",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "REQ"
						},
						{
							"withdrawMinFee": 5.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 10.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "BlockMason",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "BCPT"
						},
						{
							"withdrawMinFee": 0.1,
							"coinType": null,
							"withdrawMinAmount": 0.2,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://explorer.qtum.org/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 6,
							"infoUrl": null,
							"enable": true,
							"name": "Qtum",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "QTUM"
						},
						{
							"withdrawMinFee": 5.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 20.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Bytom",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "BTM"
						},
						{
							"withdrawMinFee": 3.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 5.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Civic",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "CVC"
						},
						{
							"withdrawMinFee": 0.01,
							"coinType": "ERC20",
							"withdrawMinAmount": 0.1,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Ethereum Fog",
							"tradePrecision": 6,
							"depositRemark": null,
							"enableWithdraw": false,
							"enableDeposit": false,
							"coin": "ETF"
						},
						{
							"withdrawMinFee": 0.5,
							"coinType": "ERC20",
							"withdrawMinAmount": 1.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "TenXPay",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "PAY"
						},
						{
							"withdrawMinFee": 0.5,
							"coinType": "ERC20",
							"withdrawMinAmount": 2.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "EOS",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": false,
							"enableDeposit": false,
							"coin": "EOS"
						},
						{
							"withdrawMinFee": 20.0,
							"coinType": "ERC20",
							"withdrawMinAmount": 100.0,
							"withdrawRemark": "",
							"orgAddress": null,
							"txUrl": "https://etherscan.io/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 12,
							"infoUrl": null,
							"enable": true,
							"name": "Status",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": true,
							"coin": "SNT"
						},
						{
							"withdrawMinFee": 1.0,
							"coinType": null,
							"withdrawMinAmount": 1.0,
							"withdrawRemark": null,
							"orgAddress": null,
							"txUrl": "http://blackholecoin.cn:3001/tx/{txId}",
							"userAddressName": null,
							"withdrawFeeRate": 0.001,
							"confirmationCount": 6,
							"infoUrl": null,
							"enable": true,
							"name": "Black Hole Coin",
							"tradePrecision": 4,
							"depositRemark": null,
							"enableWithdraw": true,
							"enableDeposit": false,
							"coin": "BHC"
						}
					]
}